Repository viets-software-club/truffle-ai, pull requests merged in 2023-11, with the labels that each got.

#34 [META-33] Add workflow terraform-apply
  .github/workflows/terraform-apply.yml
Labels: Fix Description Format

#31 [FRONT-5] Responsive UI
  packages/ui/src/components/domain/commandinterface/Modal.tsx
  packages/ui/src/components/domain/compare/index.tsx
  packages/ui/src/components/domain/details/Card.tsx
  packages/ui/src/components/domain/details/CommunitySentiment.tsx
  packages/ui/src/components/domain/details/GithubStats.tsx
  packages/ui/src/components/domain/details/Navbar.tsx
  packages/ui/src/components/domain/details/ProjectInformation.tsx
  packages/ui/src/components/domain/details/RightSidebar.tsx
  packages/ui/src/components/domain/details/index.tsx
  packages/ui/src/components/domain/projects/EditColumns.tsx
  packages/ui/src/components/domain/projects/FilterBar.tsx
  packages/ui/src/components/domain/projects/ProjectListItem.tsx
  packages/ui/src/components/domain/projects/ProjectsTable.tsx
  packages/ui/src/components/domain/projects/Table.tsx
  packages/ui/src/components/domain/projects/TopBar.tsx
  packages/ui/src/components/domain/projects/filters/FilterSelector.tsx
  packages/ui/src/components/domain/projects/filters/SortingSelector.tsx
  packages/ui/src/components/domain/settings/AffinitySettings.tsx
  packages/ui/src/components/domain/settings/DefaultFilters.tsx
  packages/ui/src/components/domain/settings/FilterInput.tsx
  packages/ui/src/components/domain/settings/Section.tsx
  packages/ui/src/components/domain/settings/Sidebar.tsx
  packages/ui/src/components/domain/settings/SlackSettings.tsx
  packages/ui/src/components/domain/sidebar/Box.tsx
  packages/ui/src/components/domain/sidebar/MenuIcon.tsx
  packages/ui/src/components/domain/sidebar/MobileMenu.tsx
  packages/ui/src/components/domain/sidebar/MobileNavLink.tsx
  packages/ui/src/components/domain/sidebar/NavSidebar.tsx
  packages/ui/src/components/domain/sidebar/SmallSidebar.tsx
  packages/ui/src/components/domain/sidebar/index.tsx
  packages/ui/src/components/shared/Button.tsx
  packages/ui/src/components/shared/Error.tsx
  packages/ui/src/components/shared/Loading.tsx
  packages/ui/src/components/shared/Modal.tsx
  packages/ui/src/components/shared/Page.tsx
  packages/ui/src/components/shared/chart/Chart.tsx
  packages/ui/src/components/shared/chart/ChartWrapper.tsx
  packages/ui/src/pages/404.tsx
  packages/ui/src/pages/login.tsx
  packages/ui/src/pages/settings.tsx
  packages/ui/src/styles/globals.css
  packages/ui/tailwind.config.js
Labels: Verified

#39 [META-23] Improvements
  README.md
  config/scripts/install-helm-repos.sh
  design-decisions.md
  packages/ui/public/logo.png
  packages/ui/src/components/domain/compare/CategoryModal.tsx
  packages/ui/src/components/domain/compare/index.tsx
  packages/ui/src/components/domain/details/BookmarkModal.tsx
  packages/ui/src/components/domain/details/ProjectInformation.tsx
  packages/ui/src/components/domain/projects/AddProject.tsx
  packages/ui/src/components/shared/Button.tsx
  packages/ui/src/components/shared/SEO.tsx
  packages/ui/src/graphql/generated/gql.ts
  packages/ui/src/pages/_app.tsx
Labels: Verified

#49 [META-48] Fix deploy config
  .github/workflows/helm.yml
  .github/workflows/images.yml
  .github/workflows/release.yml
  .github/workflows/reusable-ghcr-image.yml
  .github/workflows/reusable-terraform-plan.yml
  .github/workflows/reusable-variables.yml
  .github/workflows/terraform-apply.yml
  .github/workflows/verify-pr.yml
  .gitignore
  .prettierignore
  _configMaps/values.commit.yml
  _configMaps/values.production.yml
  _configMaps/values.staging.yml
  config/alias/aliases.txt
  config/app-chart/Chart.lock
  config/app-chart/templates/deployment-graphql-backend.yaml
  config/app-chart/values.yaml
  config/charts/app-chart/.helmignore
  config/charts/app-chart/Chart.yaml
  config/charts/app-chart/templates/config-maps.yaml
  config/charts/app-chart/templates/cronjob-repo-job.yaml
  config/charts/app-chart/templates/deployment-graphql-backend.yaml
  config/charts/app-chart/templates/deployment-ui.yaml
  config/charts/app-chart/templates/ingress.yaml
  config/charts/app-chart/templates/secrets.yaml
  config/charts/app-chart/templates/services.yaml
  config/charts/app-chart/values.yaml
  config/charts/ingress-controller/values.yaml
  config/eslint-config-base/common.js
  config/scripts/add-ingress-controller.js
  config/scripts/get-deploy-app-cmd.ts
  config/scripts/helm/app/local.mjs
  config/scripts/helm/app/publish.mjs
  config/scripts/helm/app/uninstall-env.mjs
  config/scripts/helm/app/uninstall.mjs
  config/scripts/helm/ingress/ip.mjs
  config/scripts/helm/ingress/upgrade.mjs
  config/scripts/helm/list.mjs
  config/scripts/install-helm-repos.sh
  config/scripts/run-scripts/list.mjs
  config/scripts/update-helm-repos.sh
  config/terraform2/_configMaps/configMaps.commit.yml
  config/terraform2/_configMaps/configMaps.production.yml
  config/terraform2/_configMaps/configMaps.staging.yml
  config/variables/deno.json
  config/variables/deno.lock
  config/variables/deps.ts
  config/variables/generate-env.ts
  config/variables/generate-k8s-env.ts
  config/variables/generate-values.ts
  config/variables/secrets/secretExample.scraping-bot.yml
  config/variables/secrets/secretExample.supabase.yml
  config/variables/secrets/secretExample.ui.yml
  config/variables/source-env-and-run.sh
  config/variables/source-env-vars.sh
  config/variables/source-env.sh
  deno.json
  deno.lock
  package-lock.json
  package.json
Labels: Verified

#50 [FRONT-11] Adapt UI to allow bookmarking into multiple categories
  config/eslint-config-base/nextjs.js
  packages/ui/src/components/domain/details/BookmarkModal.tsx
  packages/ui/src/components/domain/details/ProjectInformation.tsx
  packages/ui/src/components/domain/details/index.tsx
  packages/ui/src/components/domain/projects/AddProject.tsx
  packages/ui/src/components/shared/Select.tsx
Labels: Verified

#53 [FRONT-51] Add PWA support
  .gitignore
  package-lock.json
  packages/ui/next.config.js
  packages/ui/package.json
  packages/ui/public/icons/icon-128x128.png
  packages/ui/public/icons/icon-144x144.png
  packages/ui/public/icons/icon-152x152.png
  packages/ui/public/icons/icon-192x192.png
  packages/ui/public/icons/icon-384x384.png
  packages/ui/public/icons/icon-48x48.png
  packages/ui/public/icons/icon-512x512.png
  packages/ui/public/icons/icon-72x72.png
  packages/ui/public/icons/icon-96x96.png
  packages/ui/public/manifest.json
  packages/ui/src/components/shared/SEO.tsx
  packages/ui/src/pages/_offline.tsx
Labels: Verified

#56 Staging
  .github/workflows/release.yml
  config/scripts/helm/app/publish.mjs
Labels: Fix Title Format, Fix Description Format

#57 [FRONT-5] UI improvements
  .gitignore
  config/eslint-config-base/nextjs.js
  package-lock.json
  packages/ui/next.config.js
  packages/ui/package.json
  packages/ui/src/components/domain/compare/SendToSlack.tsx
  packages/ui/src/components/domain/compare/index.tsx
  packages/ui/src/components/domain/details/BookmarkModal.tsx
  packages/ui/src/components/domain/details/CommunitySentiment.tsx
  packages/ui/src/components/domain/details/FounderItem.tsx
  packages/ui/src/components/domain/details/GithubStats.tsx
  packages/ui/src/components/domain/details/Navbar.tsx
  packages/ui/src/components/domain/details/ProjectInformation.tsx
  packages/ui/src/components/domain/details/RightSidebar.tsx
  packages/ui/src/components/domain/details/index.tsx
  packages/ui/src/components/domain/login/LoginForm.tsx
  packages/ui/src/components/domain/projects/FilterBar.tsx
  packages/ui/src/components/domain/projects/ProjectsTable.tsx
  packages/ui/src/components/domain/projects/Table.tsx
  packages/ui/src/components/domain/settings/AffinitySettings.tsx
  packages/ui/src/components/domain/settings/DefaultFilters.tsx
  packages/ui/src/components/domain/settings/EmailTemplate.tsx
  packages/ui/src/components/domain/settings/SlackSettings.tsx
  packages/ui/src/components/domain/sidebar/MobileMenu.tsx
  packages/ui/src/components/domain/sidebar/NavSidebar.tsx
  packages/ui/src/components/shared/Loading.tsx
  packages/ui/src/components/shared/Page.tsx
  packages/ui/src/components/shared/Skeleton.tsx
  packages/ui/src/components/shared/chart/ChartWrapper.tsx
  packages/ui/src/components/shared/hoc/UrqlProvider.tsx
  packages/ui/src/components/shared/hoc/withAuth.tsx
  packages/ui/src/components/shared/hoc/withUrql.tsx
  packages/ui/src/pages/_app.tsx
  packages/ui/src/pages/bookmarks.tsx
  packages/ui/src/pages/compare/[category].tsx
  packages/ui/src/pages/details/[id].tsx
  packages/ui/src/pages/index.tsx
  packages/ui/src/pages/login.tsx
  packages/ui/src/stores/useSidebarCategories.ts
  packages/ui/src/util/sendSlackNotification.ts
Labels: Verified
